$u=_.noConflict();jQuery.urldecode=function(a){return decodeURIComponent(a).replace(/\+/g," ")};jQuery.urlencode=encodeURIComponent;jQuery.getQueryParameters=function(a){"undefined"===typeof a&&(a=document.location.search);a=a.substr(a.indexOf("?")+1).split("&");for(var b={},d=0;d<a.length;d++){var c=a[d].split("=",2),g=jQuery.urldecode(c[0]);c=jQuery.urldecode(c[1]);g in b?b[g].push(c):b[g]=[c]}return b};
jQuery.fn.highlightText=function(a,b){function d(c,g){if(3===c.nodeType){var f=c.nodeValue,e=f.toLowerCase().indexOf(a);if(0<=e&&!jQuery(c.parentNode).hasClass(b)){var h=jQuery(c).closest("body, svg, foreignObject").is("svg");if(h)var k=document.createElementNS("http://www.w3.org/2000/svg","tspan");else k=document.createElement("span"),k.className=b;k.appendChild(document.createTextNode(f.substr(e,a.length)));c.parentNode.insertBefore(k,c.parentNode.insertBefore(document.createTextNode(f.substr(e+
a.length)),c.nextSibling));c.nodeValue=f.substr(0,e);h&&(f=k.getBBox(),e=document.createElementNS("http://www.w3.org/2000/svg","rect"),e.x.baseVal.value=f.x,e.y.baseVal.value=f.y,e.width.baseVal.value=f.width,e.height.baseVal.value=f.height,e.setAttribute("class",b),g.push({parent:c.parentNode,target:e}))}}else jQuery(c).is("button, select, textarea")||jQuery.each(c.childNodes,function(){d(this,g)})}for(var c=[],g=this.each(function(){d(this,c)}),h=0;h<c.length;++h)jQuery(c[h].parent).before(c[h].target);
return g};jQuery.browser||(jQuery.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},jQuery.browser={},jQuery.browser[jQuery.uaMatch(navigator.userAgent).browser]=!0);
var Documentation={init:function(){this.fixFirefoxAnchorBug();this.highlightSearchWords();this.initIndexTable()},TRANSLATIONS:{},PLURAL_EXPR:function(a){return 1===a?0:1},LOCALE:"unknown",gettext:function(a){var b=Documentation.TRANSLATIONS[a];return"undefined"===typeof b?a:"string"===typeof b?b:b[0]},ngettext:function(a,b,d){var c=Documentation.TRANSLATIONS[a];return"undefined"===typeof c?1==d?a:b:c[Documentation.PLURALEXPR(d)]},addTranslations:function(a){for(var b in a.messages)this.TRANSLATIONS[b]=
a.messages[b];this.PLURAL_EXPR=new Function("n","return +("+a.plural_expr+")");this.LOCALE=a.locale},addContextElements:function(){$("div[id] > :header:first").each(function(){$('<a class="headerlink">\u00b6</a>').attr("href","#"+this.id).attr("title",_("Permalink to this headline")).appendTo(this)});$("dt[id]").each(function(){$('<a class="headerlink">\u00b6</a>').attr("href","#"+this.id).attr("title",_("Permalink to this definition")).appendTo(this)})},fixFirefoxAnchorBug:function(){document.location.hash&&
$.browser.mozilla&&window.setTimeout(function(){document.location.href+=""},10)},highlightSearchWords:function(){var a=$.getQueryParameters(),b=a.highlight?a.highlight[0].split(/\s+/):[];if(b.length){var d=$("div.body");d.length||(d=$("body"));window.setTimeout(function(){$.each(b,function(){d.highlightText(this.toLowerCase(),"highlighted")})},10);$('<p class="highlight-link"><a href="javascript:Documentation.hideSearchWords()">'+_("Hide Search Matches")+"</a></p>").appendTo($("#searchbox"))}},initIndexTable:function(){var a=
$("img.toggler").click(function(){var a=$(this).attr("src"),d=$(this).attr("id").substr(7);$("tr.cg-"+d).toggle();"minus.png"===a.substr(-9)?$(this).attr("src",a.substr(0,a.length-9)+"plus.png"):$(this).attr("src",a.substr(0,a.length-8)+"minus.png")}).css("display","");DOCUMENTATION_OPTIONS.COLLAPSE_INDEX&&a.click()},hideSearchWords:function(){$("#searchbox .highlight-link").fadeOut(300);$("span.highlighted").removeClass("highlighted")},makeURL:function(a){return DOCUMENTATION_OPTIONS.URL_ROOT+"/"+
a},getCurrentURL:function(){var a=document.location.pathname,b=a.split(/\//);$.each(DOCUMENTATION_OPTIONS.URL_ROOT.split(/\//),function(){".."===this&&b.pop()});var d=b.join("/");return a.substring(d.lastIndexOf("/")+1,a.length-1)},initOnKeyListeners:function(){$(document).keyup(function(a){var b=document.activeElement.tagName;if("TEXTAREA"!==b&&"INPUT"!==b&&"SELECT"!==b)switch(a.keyCode){case 37:if(a=$('link[rel="prev"]').prop("href"))return window.location.href=a,!1;case 39:if(a=$('link[rel="next"]').prop("href"))return window.location.href=
a,!1}})}};_=Documentation.gettext;$(document).ready(function(){Documentation.init()});
