(function(){function u(a,c,d){if(a===c)return 0!==a||1/a==1/c;if(null==a||null==c)return a===c;a._chain&&(a=a._wrapped);c._chain&&(c=c._wrapped);if(a.isEqual&&b.isFunction(a.isEqual))return a.isEqual(c);if(c.isEqual&&b.isFunction(c.isEqual))return c.isEqual(a);var e=n.call(a);if(e!=n.call(c))return!1;switch(e){case "[object String]":return a==String(c);case "[object Number]":return a!=+a?c!=+c:0==a?1/a==1/c:a==+c;case "[object Date]":case "[object Boolean]":return+a==+c;case "[object RegExp]":return a.source==
c.source&&a.global==c.global&&a.multiline==c.multiline&&a.ignoreCase==c.ignoreCase}if("object"!=typeof a||"object"!=typeof c)return!1;for(var f=d.length;f--;)if(d[f]==a)return!0;d.push(a);f=0;var g=!0;if("[object Array]"==e){if(f=a.length,g=f==c.length)for(;f--&&(g=f in a==f in c&&u(a[f],c[f],d)););}else{if("constructor"in a!="constructor"in c||a.constructor!=c.constructor)return!1;for(var h in a)if(b.has(a,h)&&(f++,!(g=b.has(c,h)&&u(a[h],c[h],d))))break;if(g){for(h in c)if(b.has(c,h)&&!f--)break;
g=!f}}d.pop();return g}var v=this,K=v._,q={},m=Array.prototype,r=Object.prototype,k=m.slice,L=m.unshift,n=r.toString,M=r.hasOwnProperty,A=m.forEach,B=m.map,C=m.reduce,D=m.reduceRight,E=m.filter,F=m.every,G=m.some,t=m.indexOf,H=m.lastIndexOf;r=Array.isArray;var N=Object.keys,w=Function.prototype.bind,b=function(a){return new p(a)};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=b),exports._=b):v._=b;b.VERSION="1.3.1";var l=b.each=b.forEach=function(a,
c,d){if(null!=a)if(A&&a.forEach===A)a.forEach(c,d);else if(a.length===+a.length)for(var e=0,f=a.length;e<f&&!(e in a&&c.call(d,a[e],e,a)===q);e++);else for(e in a)if(b.has(a,e)&&c.call(d,a[e],e,a)===q)break};b.map=b.collect=function(a,c,b){var d=[];if(null==a)return d;if(B&&a.map===B)return a.map(c,b);l(a,function(a,e,h){d[d.length]=c.call(b,a,e,h)});a.length===+a.length&&(d.length=a.length);return d};b.reduce=b.foldl=b.inject=function(a,c,d,e){var f=2<arguments.length;null==a&&(a=[]);if(C&&a.reduce===
C)return e&&(c=b.bind(c,e)),f?a.reduce(c,d):a.reduce(c);l(a,function(a,b,k){f?d=c.call(e,d,a,b,k):(d=a,f=!0)});if(!f)throw new TypeError("Reduce of empty array with no initial value");return d};b.reduceRight=b.foldr=function(a,c,d,e){var f=2<arguments.length;null==a&&(a=[]);if(D&&a.reduceRight===D)return e&&(c=b.bind(c,e)),f?a.reduceRight(c,d):a.reduceRight(c);var g=b.toArray(a).reverse();e&&!f&&(c=b.bind(c,e));return f?b.reduce(g,c,d,e):b.reduce(g,c)};b.find=b.detect=function(a,c,b){var d;I(a,function(a,
e,h){if(c.call(b,a,e,h))return d=a,!0});return d};b.filter=b.select=function(a,c,b){var d=[];if(null==a)return d;if(E&&a.filter===E)return a.filter(c,b);l(a,function(a,e,h){c.call(b,a,e,h)&&(d[d.length]=a)});return d};b.reject=function(a,c,b){var d=[];if(null==a)return d;l(a,function(a,e,h){c.call(b,a,e,h)||(d[d.length]=a)});return d};b.every=b.all=function(a,c,b){var d=!0;if(null==a)return d;if(F&&a.every===F)return a.every(c,b);l(a,function(a,e,h){if(!(d=d&&c.call(b,a,e,h)))return q});return d};
var I=b.some=b.any=function(a,c,d){c||(c=b.identity);var e=!1;if(null==a)return e;if(G&&a.some===G)return a.some(c,d);l(a,function(a,b,h){if(e||(e=c.call(d,a,b,h)))return q});return!!e};b.include=b.contains=function(a,c){var b=!1;return null==a?b:t&&a.indexOf===t?-1!=a.indexOf(c):b=I(a,function(a){return a===c})};b.invoke=function(a,c){var d=k.call(arguments,2);return b.map(a,function(a){return(b.isFunction(c)?c||a:a[c]).apply(a,d)})};b.pluck=function(a,c){return b.map(a,function(a){return a[c]})};
b.max=function(a,c,d){if(!c&&b.isArray(a))return Math.max.apply(Math,a);if(!c&&b.isEmpty(a))return-Infinity;var e={computed:-Infinity};l(a,function(a,b,h){b=c?c.call(d,a,b,h):a;b>=e.computed&&(e={value:a,computed:b})});return e.value};b.min=function(a,c,d){if(!c&&b.isArray(a))return Math.min.apply(Math,a);if(!c&&b.isEmpty(a))return Infinity;var e={computed:Infinity};l(a,function(a,b,h){b=c?c.call(d,a,b,h):a;b<e.computed&&(e={value:a,computed:b})});return e.value};b.shuffle=function(a){var b=[],d;
l(a,function(a,c,g){0==c?b[0]=a:(d=Math.floor(Math.random()*(c+1)),b[c]=b[d],b[d]=a)});return b};b.sortBy=function(a,c,d){return b.pluck(b.map(a,function(a,b,g){return{value:a,criteria:c.call(d,a,b,g)}}).sort(function(a,b){var c=a.criteria,d=b.criteria;return c<d?-1:c>d?1:0}),"value")};b.groupBy=function(a,c){var d={},e=b.isFunction(c)?c:function(a){return a[c]};l(a,function(a,b){var c=e(a,b);(d[c]||(d[c]=[])).push(a)});return d};b.sortedIndex=function(a,c,d){d||(d=b.identity);for(var e=0,f=a.length;e<
f;){var g=e+f>>1;d(a[g])<d(c)?e=g+1:f=g}return e};b.toArray=function(a){return a?a.toArray?a.toArray():b.isArray(a)||b.isArguments(a)?k.call(a):b.values(a):[]};b.size=function(a){return b.toArray(a).length};b.first=b.head=function(a,b,d){return null==b||d?a[0]:k.call(a,0,b)};b.initial=function(a,b,d){return k.call(a,0,a.length-(null==b||d?1:b))};b.last=function(a,b,d){return null==b||d?a[a.length-1]:k.call(a,Math.max(a.length-b,0))};b.rest=b.tail=function(a,b,d){return k.call(a,null==b||d?1:b)};b.compact=
function(a){return b.filter(a,function(a){return!!a})};b.flatten=function(a,c){return b.reduce(a,function(a,e){if(b.isArray(e))return a.concat(c?e:b.flatten(e));a[a.length]=e;return a},[])};b.without=function(a){return b.difference(a,k.call(arguments,1))};b.uniq=b.unique=function(a,c,d){d=d?b.map(a,d):a;var e=[];b.reduce(d,function(d,g,h){0!=h&&(!0===c?b.last(d)==g:b.include(d,g))||(d[d.length]=g,e[e.length]=a[h]);return d},[]);return e};b.union=function(){return b.uniq(b.flatten(arguments,!0))};
b.intersection=b.intersect=function(a){var c=k.call(arguments,1);return b.filter(b.uniq(a),function(a){return b.every(c,function(c){return 0<=b.indexOf(c,a)})})};b.difference=function(a){var c=b.flatten(k.call(arguments,1));return b.filter(a,function(a){return!b.include(c,a)})};b.zip=function(){for(var a=k.call(arguments),c=b.max(b.pluck(a,"length")),d=Array(c),e=0;e<c;e++)d[e]=b.pluck(a,""+e);return d};b.indexOf=function(a,c,d){if(null==a)return-1;var e;if(d)return d=b.sortedIndex(a,c),a[d]===c?
d:-1;if(t&&a.indexOf===t)return a.indexOf(c);d=0;for(e=a.length;d<e;d++)if(d in a&&a[d]===c)return d;return-1};b.lastIndexOf=function(a,b){if(null==a)return-1;if(H&&a.lastIndexOf===H)return a.lastIndexOf(b);for(var c=a.length;c--;)if(c in a&&a[c]===b)return c;return-1};b.range=function(a,b,d){1>=arguments.length&&(b=a||0,a=0);d=arguments[2]||1;for(var c=Math.max(Math.ceil((b-a)/d),0),f=0,g=Array(c);f<c;)g[f++]=a,a+=d;return g};var J=function(){};b.bind=function(a,c){var d;if(a.bind===w&&w)return w.apply(a,
k.call(arguments,1));if(!b.isFunction(a))throw new TypeError;var e=k.call(arguments,2);return d=function(){if(!(this instanceof d))return a.apply(c,e.concat(k.call(arguments)));J.prototype=a.prototype;var b=new J,g=a.apply(b,e.concat(k.call(arguments)));return Object(g)===g?g:b}};b.bindAll=function(a){var c=k.call(arguments,1);0==c.length&&(c=b.functions(a));l(c,function(c){a[c]=b.bind(a[c],a)});return a};b.memoize=function(a,c){var d={};c||(c=b.identity);return function(){var e=c.apply(this,arguments);
return b.has(d,e)?d[e]:d[e]=a.apply(this,arguments)}};b.delay=function(a,b){var c=k.call(arguments,2);return setTimeout(function(){return a.apply(a,c)},b)};b.defer=function(a){return b.delay.apply(b,[a,1].concat(k.call(arguments,1)))};b.throttle=function(a,c){var d,e,f,g,h,k=b.debounce(function(){h=g=!1},c);return function(){d=this;e=arguments;f||(f=setTimeout(function(){f=null;h&&a.apply(d,e);k()},c));g?h=!0:a.apply(d,e);k();g=!0}};b.debounce=function(a,b){var c;return function(){var d=this,f=arguments;
clearTimeout(c);c=setTimeout(function(){c=null;a.apply(d,f)},b)}};b.once=function(a){var b=!1,d;return function(){if(b)return d;b=!0;return d=a.apply(this,arguments)}};b.wrap=function(a,b){return function(){var c=[a].concat(k.call(arguments,0));return b.apply(this,c)}};b.compose=function(){var a=arguments;return function(){for(var b=arguments,d=a.length-1;0<=d;d--)b=[a[d].apply(this,b)];return b[0]}};b.after=function(a,b){return 0>=a?b():function(){if(1>--a)return b.apply(this,arguments)}};b.keys=
N||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var c=[],d;for(d in a)b.has(a,d)&&(c[c.length]=d);return c};b.values=function(a){return b.map(a,b.identity)};b.functions=b.methods=function(a){var c=[],d;for(d in a)b.isFunction(a[d])&&c.push(d);return c.sort()};b.extend=function(a){l(k.call(arguments,1),function(b){for(var c in b)a[c]=b[c]});return a};b.defaults=function(a){l(k.call(arguments,1),function(b){for(var c in b)null==a[c]&&(a[c]=b[c])});return a};b.clone=function(a){return b.isObject(a)?
b.isArray(a)?a.slice():b.extend({},a):a};b.tap=function(a,b){b(a);return a};b.isEqual=function(a,b){return u(a,b,[])};b.isEmpty=function(a){if(b.isArray(a)||b.isString(a))return 0===a.length;for(var c in a)if(b.has(a,c))return!1;return!0};b.isElement=function(a){return!(!a||1!=a.nodeType)};b.isArray=r||function(a){return"[object Array]"==n.call(a)};b.isObject=function(a){return a===Object(a)};b.isArguments=function(a){return"[object Arguments]"==n.call(a)};b.isArguments(arguments)||(b.isArguments=
function(a){return!(!a||!b.has(a,"callee"))});b.isFunction=function(a){return"[object Function]"==n.call(a)};b.isString=function(a){return"[object String]"==n.call(a)};b.isNumber=function(a){return"[object Number]"==n.call(a)};b.isNaN=function(a){return a!==a};b.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"==n.call(a)};b.isDate=function(a){return"[object Date]"==n.call(a)};b.isRegExp=function(a){return"[object RegExp]"==n.call(a)};b.isNull=function(a){return null===a};b.isUndefined=
function(a){return void 0===a};b.has=function(a,b){return M.call(a,b)};b.noConflict=function(){v._=K;return this};b.identity=function(a){return a};b.times=function(a,b,d){for(var c=0;c<a;c++)b.call(d,c)};b.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};b.mixin=function(a){l(b.functions(a),function(c){O(c,b[c]=a[c])})};var P=0;b.uniqueId=function(a){var b=P++;return a?a+b:b};b.templateSettings=
{evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var x=/.^/,y=function(a){return a.replace(/\\\\/g,"\\").replace(/\\'/g,"'")};b.template=function(a,c){var d=b.templateSettings;d="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(d.escape||x,function(a,b){return"',_.escape("+y(b)+"),'"}).replace(d.interpolate||x,function(a,b){return"',"+y(b)+",'"}).replace(d.evaluate||x,function(a,
b){return"');"+y(b).replace(/[\r\n\t]/g," ")+";__p.push('"}).replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');";var e=new Function("obj","_",d);return c?e(c,b):function(a){return e.call(this,a,b)}};b.chain=function(a){return b(a).chain()};var p=function(a){this._wrapped=a};b.prototype=p.prototype;var z=function(a,c){return c?b(a).chain():a},O=function(a,c){p.prototype[a]=function(){var a=k.call(arguments);L.call(a,this._wrapped);return z(c.apply(b,a),this._chain)}};
b.mixin(b);l("pop push reverse shift sort splice unshift".split(" "),function(a){var b=m[a];p.prototype[a]=function(){var c=this._wrapped;b.apply(c,arguments);var e=c.length;"shift"!=a&&"splice"!=a||0!==e||delete c[0];return z(c,this._chain)}});l(["concat","join","slice"],function(a){var b=m[a];p.prototype[a]=function(){return z(b.apply(this._wrapped,arguments),this._chain)}});p.prototype.chain=function(){this._chain=!0;return this};p.prototype.value=function(){return this._wrapped}}).call(this);
