version: "3"
services:

  postgres:
    build: ./database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  api:
    build: ./src
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 2; done; python3 app.py'
    environment:
      - ENV=development
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - postgres
