# Need pip to be installed
setup:
	pip install -r requirements.txt

sudo-setup:
	sudo pip install -r requirements.txt

# Check whether locations are in UCLA or not!
ucla:
	python tkinterUCLA.py

# Check whether location data is right!
unknown:
	python tkinterLocs.py

# Check whether event has free food!
food:
	python tkinterFood.py
