
abbreviations_map = {
	'aca': [''],
	'asme': ['american society of mechanical engineers'],
	'ackerman union': ['au', 'ackerman'],
	'afrikan student union': ['asu'],
	'alpha gamma omega ucla': ['ago'],
	'alpha kappa psi - ucla alpha upsilon chapter': ['akp'],
	'alpha tau delta - gamma chapter': ['atd'],
	'american indian studies center library': ['aiscl', 'aisc'],
	'anderson school of management': ['anderson'],
	'architecture & urban design': ['aud'],
	'ashe student health center': ['ashe', 'ashe center'],
	'asian american studies center library': ['aascl', 'aasc'],
	'asian pacific coalition': ['apc'],
	'bj\'s restaurant and brewhouse': ['bj'],
	'boelter hall': ['bh'],
	'bplate dining hall': ['bplate'],
	'brain research institute': ['bri'],
	'breathe los angeles at ucla': ['breathe la', 'breath la'],
	'bruin spacecraft group': ['bruinspace', 'bruin space'],
	'cafe 1919': ['1919'],
	'coco fresh tea & juice westwood': ['coco'],
	'creative labs': ['cl'],
	'delta sigma pi': ['dsp'],
	'design media arts': ['desma'],
	'doris stein eye research center': ['dserc'],
	'east asian library': ['eal'],
	'english reading room': ['grace m. hunt memorial english reading room ', 'err'],
	'facilities management building': ['fmb', 'fm'],
	'fellowship for international service & health - fish': ['fish'],
	'film & television archive': ['arsc'],
	'foshay learning center': ['flc'],
	'friends of the semel institute for neuroscience and  human behavior': ['friends of npi'],
	'gamma rho lambda - zeta chapter at ucla': ['grl'],
	'gonda (goldschmied) neuroscience and genetics research center': ['gonda'],
	'gonda family library': ['gfl'],
	'humanities building ucla': ['kaplan', 'kaplan hall', 'kaplan building'],
	'international student association / isa at ucla': ['isa'],
	'iranian student group at ucla': ['isg', 'isg at ucla'],
	'james west alumni center aka jwac': ['jwac'],
	'latino business student association at ucla': ['lbsa'],
	'law student bar association': ['lsba', 'sba'],
	'learning resource center': ['lrc'],
	'los angeles': ['la'],
	'los angeles ski and board club': ['lasbc'],
	'macdonald medical research laboratory': ['mmrl', 'mrl'],
	'muslim student association at ucla': ['msa'],
	'near eastern languages & cultures': ['nelc'],
	'new student & transition programs': ['nstp'],
	'phi delta theta - ucla': ['pdt'],
	'phi kappa sigma ucla': ['pks'],
	'phi sigma rho': ['psr'],
	'pi kappa phi ucla': ['pkp'],
	'reed neurological research center': ['rnrc'],
	'rendezvous': ['rende'],
	'rocco\'s tavern': ['roccos'],
	'spear - samahang pilipino education and retention': ['spear'],
	'science and technology research building': ['strb'],
	'semel institute for neuroscience and human behavior': ['semel'],
	'sigma alpha mu at ucla': ['sam'],
	'students with dependents program at the ucla bruin resource center': ['swd'],
	'student committee for the arts at ucla': ['sca'],
	'the association of ucla gamers - augment': ['augment'],
	'ucla center for brazilian studies': ['lcbs', 'cbs'],
	'ucla community programs office': ['cpo'],
	'ucla engineering graduate students association': ['egsa'],
	'ucla institute of the environment and sustainability': ['ioes'],
	'ucla intergroup relations program (igr)': ['igr'],
	'ucla kappa alpha theta': ['kat'],
	'ucla kinross recreation center (krec)': ['krec'],
	'ucla mindful awareness research center': ['marc'],
	'ucla pi beta phi': ['pbp'],
	'ucla police department': ['ucpd'],
	'ucla undergraduate research center-humanities, arts, and social sciences': ['ucla ugresearch', 'ugr'],
	'undergraduate astronomical society': ['uas'],
	'undocumented student program': ['usp'],
	'westwood branch - los angeles public library': ['lapl'],
	'writing success program at ucla': ['wsp']
}